version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm run build

      - save_cache:
          paths:
            - node_modules
            - dist
            - package.json
            - firebase.json
            - .firebaserc
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 

  deploy-job:
       docker:
         - image: circleci/node:12.4
       working_directory: ~/repo 
       steps:
         - restore_cache:
             keys:
              - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 
         - run:
             name: show directory 
             command: pwd
         - run:
             name: Install Firebase
             command: sudo npm install -g firebase-tools
         - run:
             name: look in directory
             command: ls -ltr
         - run:
             name: Deploy Master to Firebase
             command: firebase deploy --token=$FKEY --non-interactive
             

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
